#!/bin/bash
cp /crd-session /home/chrome/.chrome-remote-desktop-session
ln -s /home/chrome/.config/chrome-remote-desktop/host#*.json /home/chrome/.config/chrome-remote-desktop/host##.json
/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord-crdonly.conf

# g_host_hash = hashlib.md5(socket.gethostname()).hexdigest()
#  options.config = os.path.join(CONFIG_DIR, "host#%s.json" % g_host_hash)